#!/usr/bin/env python3

def calculate_sum(i):
    return sum([9*i - 2*k for k in range(1, 5)])

# Find the value of i for which the sum is 2
for potential_i in range(-100, 100):
    if calculate_sum(potential_i) == 2:
        i_value = potential_i
        break

print(i_value)